# @name get-prompts
GET http://localhost:8080/prompts

###

# @name post-videos
POST http://127.0.0.1:8080/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="x.mp3"
Content-Type: audio/mpeg

< ./x.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://127.0.0.1:8080/videos/clmp53qd10000i04dzsly0haa/transcription
Content-Type: application/json

{
    "prompt": "reflexao"
}
